# Generated by Django 4.1.7 on 2023-11-06 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_livechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechat',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
