# Generated by Django 4.1.7 on 2023-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_livechat_send_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Blog-Images')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('author', models.CharField(max_length=100)),
                ('author_img', models.ImageField(upload_to='Authors_images')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
