# Generated by Django 4.1.7 on 2023-11-10 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('member_img', models.ImageField(upload_to='Team_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('description', models.TextField()),
            ],
        ),
    ]
