# Generated by Django 4.1.7 on 2023-11-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_comment_situations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='situations',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
    ]
